// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9gjuZ9XZww8YR74eS7TlSQqnR0B5SYjI',
    appId: '1:382446275425:web:634098b4d35d2f89edd320',
    messagingSenderId: '382446275425',
    projectId: 'hems-03d',
    authDomain: 'hems-03d.firebaseapp.com',
    storageBucket: 'hems-03d.firebasestorage.app',
    measurementId: 'G-TNSVRFG8S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi3oCRZf_3tgP2zWHngSXNusCGVlUCi-E',
    appId: '1:382446275425:android:d69ffb43d319aab4edd320',
    messagingSenderId: '382446275425',
    projectId: 'hems-03d',
    storageBucket: 'hems-03d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscYB31jEJepcTcEu-WD2HDHErb5CvTik',
    appId: '1:382446275425:ios:b9d9d77211d63334edd320',
    messagingSenderId: '382446275425',
    projectId: 'hems-03d',
    storageBucket: 'hems-03d.firebasestorage.app',
    iosBundleId: 'com.example.hemsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDscYB31jEJepcTcEu-WD2HDHErb5CvTik',
    appId: '1:382446275425:ios:b9d9d77211d63334edd320',
    messagingSenderId: '382446275425',
    projectId: 'hems-03d',
    storageBucket: 'hems-03d.firebasestorage.app',
    iosBundleId: 'com.example.hemsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9gjuZ9XZww8YR74eS7TlSQqnR0B5SYjI',
    appId: '1:382446275425:web:c95a35f0b8d24f33edd320',
    messagingSenderId: '382446275425',
    projectId: 'hems-03d',
    authDomain: 'hems-03d.firebaseapp.com',
    storageBucket: 'hems-03d.firebasestorage.app',
    measurementId: 'G-4CTRN7HP9B',
  );
}
